### ISSUE TITLE
Dragging weapon to macro bar shows options box but does not create macro

### ISSUE THREAD

**Issue by AWD-2** [toastygm/HarnMaster-3-FoundryVTT#339]
Dragging a weapon from a character sheet to the macro bar displays the options box, but selecting the option does not create the macro as it did in the past.  It seems to create a New Macro in the macro folder next to the hotbar.

**Comment by HOOS-karl** [comment]
I am having the same issue and verified it this morning.

**Comment by scooper4711** [comment]
It's either the same as or closely related to #330

**Comment by scooper4711** [comment]
```
macros.js:54 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
[Detected 1 package: system:hm3]
    at applyMacro (macros.js:54:38)
    at Object.callback (macros.js:80:38)
    at Dialog.submit (foundry.js:43918:35)
    at Dialog._onClickButton (foundry.js:43881:10)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
```
